development:
  app_id: 078HqAmNZVARRYGusP5QB1YyMIhqESGjwgIxWKmn
  master_key: i3ujcwElMpT7DbkYyqhk2KDjoj9OxpiHYDbtUvPc

test:
  app_id: pqullTmHbf0Z2uu8MabKj78wlPA7pe5UIRGJX6dE
  master_key: qzyel7OkKhVP9HnGwfeiu3DLoH01m2Scz1dLq6og

production:
  app_id: uOMVUubVeaet3mrR922TmAJletzG50fl6E6FtkPy
  master_key: yNzaZkKUO1mSYFVyNU4TUVUduFSAYQYgvwrTf6Ic